version: "2"
services:

  picard-website:
    build:
      context: ..
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DEPLOY_ENV: "prod"
      SERVICE_3031_NAME: "picard-website"
      SERVICE_3031_CHECK_TCP: "true"
      SERVICE_3031_CHECK_INTERVAL: "15s"
      SERVICE_3031_CHECK_TIMEOUT: "3s"
    network_mode: bridge
    ports:
      - "13034:3031"
