version: "2"
services:

  db:
    extends:
      file: ./common.yml
      service: db
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "80:8080"
    depends_on:
      - db
