abbreviations:
  type: list
  default: 'rtfm,Read The Fine Manual|tl;dr,Too Long; Didn''t Read'
  description:
    en: "List of abbreviations to add `abbr` tags to in posts, as well as their meanings."
    da: "Liste over forkortelser der skal tilføjes `abbr` tags til i indlæg, samt deres betydninger."
