sudo: required

language: python

services:
  - docker


install:
  - docker-compose -f test/docker-compose.py2.yml -p brainzutils_py2_test build
  - docker-compose -f test/docker-compose.py3.yml -p brainzutils_py3_test build

script:
  - docker-compose -f test/docker-compose.py2.yml -p brainzutils_py2_test up -d redis
  - docker-compose -f test/docker-compose.py2.yml -p brainzutils_py2_test run --rm test
      dockerize
      -wait tcp://redis:6379 -timeout 10s
      py.test
  - docker-compose -f test/docker-compose.py2.yml -p brainzutils_py2_test down

  - sleep 2

  - docker-compose -f test/docker-compose.py3.yml -p brainzutils_py3_test up -d redis
  - docker-compose -f test/docker-compose.py3.yml -p brainzutils_py3_test run --rm test
      dockerize
      -wait tcp://redis:6379 -timeout 10s
      py.test
  - docker-compose -f test/docker-compose.py3.yml -p brainzutils_py3_test down
