(ns musicbrainz-importer.mbserver-table-defs)

(def table-defs
  {:alternative_release
   [:id
    :gid
    :release
    :name
    :artist_credit
    :type
    :language
    :script
    :comment]
   :alternative_release_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :alternative_medium
   [:id
    :medium
    :alternative_release
    :name]
   :alternative_track
   [:id
    :name
    :artist_credit
    :ref_count]
   :alternative_medium_track
   [:alternative_medium
    :track
    :alternative_track]
   :annotation
   [:id
    :editor
    :text
    :changelog
    :created]
   :application
   [:id
    :owner
    :name
    :oauth_id
    :oauth_secret
    :oauth_redirect_uri]
   :area_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :area
   [:id
    :gid
    :name
    :type
    :edits_pending
    :last_updated
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :ended
    :comment]
   :area_gid_redirect
   [:gid
    :new_id
    :created]
   :area_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :area_alias
   [:id
    :area
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale
    :ended]
   :area_annotation
   [:area
    :annotation]
   :area_attribute_type
   [:id
    :name
    :comment
    :free_
    :parent
    :child_order
    :description
    :gid]
   :area_attribute_type_allowed_value
   [:id
    :area_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :area_attribute
   [:id
    :area
    :area_attribute_type
    :area_attribute_type_allowed_value
    :area_attribute_]
   :area_tag
   [:area
    :tag
    :count
    :last_updated]
   :area_tag_raw
   [:area
    :editor
    :tag
    :is_upvote]
   :artist
   [:id
    :gid
    :name
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :type
    :area
    :gender
    :comment
    :edits_pending
    :last_updated
    :ended
    :begin_area
    :end_area]
   :artist_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :artist_alias
   [:id
    :artist
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale
    :ended]
   :artist_annotation
   [:artist
    :annotation]
   :artist_attribute_type
   [:id
    :name
    :comment
    :free_text
    :parent
    :child_order
    :description
    :gid]
   :artist_attribute_type_allowed_value
   [:id
    :artist_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :artist_attribute
   [:id
    :artist
    :artist_attribute_type
    :artist_attribute_type_allowed_value
    :artist_attribute_text]
   :artist_ipi
   [:artist
    :ipi
    :edits_pending
    :created]
   :artist_isni
   [:artist
    :isni
    :edits_pending
    :created]
   :artist_meta
   [:id
    :rating
    :rating_count]
   :artist_tag
   [:artist
    :tag
    :count
    :last_updated]
   :artist_rating_raw
   [:artist
    :editor
    :rating]
   :artist_tag_raw
   [:artist
    :editor
    :tag
    :is_upvote]
   :artist_credit
   [:id
    :name
    :artist_count
    :ref_count
    :created
    :edits_pending]
   :artist_credit_name
   [:artist_credit
    :position
    :artist
    :name
    :join_phrase]
   :artist_gid_redirect
   [:gid
    :new_id
    :created]
   :artist_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :autoeditor_election
   [:id
    :candidate
    :proposer
    :seconder_1
    :seconder_2
    :status             ;; 1 : has proposer, 2 : has seconder_1, 3 : has seconder_2 (voting open), 4 : accepted!, 5 : rejected, 6 : cancelled (by proposer)
    :yes_votes
    :no_votes
    :propose_time
    :open_time
    :close_time]
   :autoeditor_election_vote
   [:id
    :autoeditor_election
    :voter
    :vote
    :vote_time]
   :cdtoc
   [:id
    :discid
    :freedb_id
    :track_count
    :leadout_offset
    :track_offset
    :degraded
    :created]
   :cdtoc_raw
   [:id
    :release
    :discid
    :track_count
    :leadout_offset
    :track_offset]
   :country_area
   [:area]
   :deleted_entity
   [:gid
    :data
    :deleted_at]
   :edit
   [:id
    :editor
    :type
    :status
    :autoedit
    :open_time
    :close_time
    :expire_time
    :language
    :quality]
   :edit_data
   [:edit
    :data]
   :edit_note
   [:id
    :editor
    :edit
    :text
    :post_time]
   :edit_note_recipient
   [:recipient
    :edit_note]
   :edit_area
   [:edit
    :area]
   :edit_artist
   [:edit
    :artist
    :status]
   :edit_event
   [:edit
    :event]
   :edit_instrument
   [:edit
    :instrument]
   :edit_label
   [:edit
    :label
    :status]
   :edit_place
   [:edit
    :place]
   :edit_release
   [:edit
    :release]
   :edit_release_group
   [:edit
    :release_group]
   :edit_recording
   [:edit
    :recording]
   :edit_series
   [:edit
    :series]
   :edit_work
   [:edit
    :work]
   :edit_url
   [:edit
    :url]
   :editor
   [:id
    :name
    :privs
    :email
    :website
    :bio
    :member_since
    :email_confirm_date
    :last_login_date
    :last_updated
    :birth_date
    :gender
    :area
    :password
    :ha1
    :deleted]
   :old_editor_name
   [:name]
   :editor_language
   [:editor
    :language
    :fluency]
   :editor_preference
   [:id
    :editor
    :name
    :value]
   :editor_subscribe_artist
   [:id
    :editor
    :artist
    :last_edit_sent]
   :editor_subscribe_artist_deleted
   [:editor
    :gid
    :deleted_by]
   :editor_subscribe_collection
   [:id
    :editor
    :collection
    :last_edit_sent
    :available
    :last_seen_name]
   :editor_subscribe_label
   [:id
    :editor
    :label
    :last_edit_sent]
   :editor_subscribe_label_deleted
   [:editor
    :gid
    :deleted_by]
   :editor_subscribe_editor
   [:id
    :editor
    :subscribed_editor
    :last_edit_sent]
   :editor_subscribe_series
   [:id
    :editor
    :series
    :last_edit_sent]
   :editor_subscribe_series_deleted
   [:editor
    :gid
    :deleted_by]
   :event
   [:id
    :gid
    :name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :time
    :type
    :cancelled
    :setlist
    :comment
    :edits_pending
    :last_updated
    :ended]
   :event_meta
   [:id
    :rating
    :rating_count
    :event_art_presence]
   :event_rating_raw
   [:event
    :editor
    :rating]
   :event_tag_raw
   [:event
    :editor
    :tag
    :is_upvote]
   :event_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :event_alias
   [:id
    :event
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale
    :ended]
   :event_annotation
   [:event
    :annotation]
   :event_attribute_type
   [:id
    :name
    :comment
    :free_
    :parent
    :child_order
    :description
    :gid]
   :event_attribute_type_allowed_value
   [:id
    :event_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :event_attribute
   [:id
    :event
    :event_attribute_type
    :event_attribute_type_allowed_value
    :event_attribute_text]
   :event_gid_redirect
   [:gid
    :new_id
    :created]
   :event_tag
   [:event
    :tag
    :count
    :last_updated]
   :event_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :gender
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :genre
   [:id
    :gid
    :name
    :comment
    :edits_pending
    :last_updated]
   :genre_alias
   [:id
    :genre
    :name
    :locale
    :edits_pending
    :last_updated
    :primary_for_locale]
   :instrument_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :instrument
   [:id
    :gid
    :name
    :type
    :edits_pending
    :last_updated
    :comment
    :description]
   :instrument_gid_redirect
   [:gid
    :new_id
    :created]
   :instrument_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :instrument_alias
   [:id
    :instrument
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale
    :ended]
   :instrument_annotation
   [:instrument
    :annotation]
   :instrument_attribute_type
   [:id
    :name
    :comment
    :free_
    :parent
    :child_order
    :description
    :gid]
   :instrument_attribute_type_allowed_value
   [:id
    :instrument_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :instrument_attribute
   [:id
    :instrument
    :instrument_attribute_type
    :instrument_attribute_type_allowed_value
    :instrument_attribute_text]
   :instrument_tag
   [:instrument
    :tag
    :count
    :last_updated]
   :instrument_tag_raw
   [:instrument
    :editor
    :tag
    :is_upvote]
   :iso_3166_1
   [:area
    :code]
   :iso_3166_2
   [:area
    :code]
   :iso_3166_3
   [:area
    :code]
   :isrc
   [:id
    :recording
    :isrc
    :source
    :edits_pending
    :created]
   :iswc
   [:id
    :work
    :iswc
    :source
    :edits_pending
    :created]
   :l_area_area
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_artist
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_event
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_instrument
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_label
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_place
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_recording
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_release
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_release_group
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_area_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_artist
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_event
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_instrument
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_label
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_place
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_recording
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_release
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_release_group
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_artist_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_event
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_instrument
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_label
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_place
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_recording
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_release
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_release_group
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_event_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_label_label
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_instrument_instrument
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_instrument_label
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_instrument_place
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_instrument_recording
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_instrument_release
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_instrument_release_group
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_instrument_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_instrument_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_instrument_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_label_place
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_label_recording
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_label_release
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_label_release_group
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_label_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_label_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_label_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_place_place
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_place_recording
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_place_release
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_place_release_group
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_place_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_place_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_place_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_recording_recording
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_recording_release
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_recording_release_group
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_recording_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_recording_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_recording_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_release_release
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_release_release_group
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_release_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_release_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_release_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_release_group_release_group
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_release_group_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_release_group_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_release_group_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_series_series
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_series_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_series_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_url_url
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_url_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :l_work_work
   [:id
    :link
    :entity0
    :entity1
    :edits_pending
    :last_updated
    :link_order
    :entity0_credit
    :entity1_credit]
   :label
   [:id
    :gid
    :name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :label_code
    :type
    :area
    :comment
    :edits_pending
    :last_updated
    :ended]

   :label_rating_raw
   [:label
    :editor
    :rating]
   :label_tag_raw
   [:label
    :editor
    :tag
    :is_upvote]
   :label_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :label_alias
   [:id
    :label
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale
    :ended]
   :label_annotation
   [:label
    :annotation]
   :label_attribute_type
   [:id
    :name
    :comment
    :free_text
    :parent
    :child_order
    :description
    :gid]
   :label_attribute_type_allowed_value
   [:id
    :label_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :label_attribute
   [:id
    :label
    :label_attribute_type
    :label_attribute_type_allowed_value
    :label_attribute_]
   :label_ipi
   [:label
    :ipi
    :edits_pending
    :created]
   :label_isni
   [:label
    :isni
    :edits_pending
    :created]
   :label_meta
   [:id
    :rating
    :rating_count]
   :label_gid_redirect
   [:gid
    :new_id
    :created]
   :label_tag
   [:label
    :tag
    :count
    :last_updated]
   :label_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :language
   [:id
    :iso_code_2t
    :iso_code_2b
    :iso_code_1
    :name
    :frequency
    :iso_code_3]
   :link
   [:id
    :link_type
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :attribute_count
    :created
    :ended]
   :link_attribute
   [:link
    :attribute_type
    :created]
   :link_attribute_type
   [:id
    :parent
    :root
    :child_order
    :gid
    :name
    :description
    :last_updated]
   :link_creditable_attribute_type
   [:attribute_type]
   :link_attribute_credit
   [:link
    :attribute_type
    :credited_as]
   :link__attribute_type
   [:attribute_type]
   :link_attribute__value
   [:link
    :attribute_type
    :text_value]
   :link_type
   [:id
    :parent
    :child_order
    :gid
    :entity_type0
    :entity_type1
    :name
    :description
    :link_phrase
    :reverse_link_phrase
    :long_link_phrase
    :priority
    :last_updated
    :is_deprecated
    :has_dates
    :entity0_cardinality
    :entity1_cardinality]
   :link_type_attribute_type
   [:link_type
    :attribute_type
    :min
    :max
    :last_updated]
   :editor_collection
   [:id
    :gid
    :editor
    :name
    :public
    :description
    :type]
   :editor_collection_type
   [:id
    :name
    :entity_type
    :parent
    :child_order
    :description
    :gid]
   :editor_collection_collaborator
   [:collection
    :editor]
   :editor_collection_area
   [:collection
    :area
    :added
    :position
    :comment]
   :editor_collection_artist
   [:collection
    :artist
    :added
    :position
    :comment]
   :editor_collection_event
   [:collection
    :event
    :added
    :position
    :comment]
   :editor_collection_instrument
   [:collection
    :instrument
    :added
    :position
    :comment]
   :editor_collection_label
   [:collection
    :label
    :added
    :position
    :comment]
   :editor_collection_place
   [:collection
    :place
    :added
    :position
    :comment]
   :editor_collection_recording
   [:collection
    :recording
    :added
    :position
    :comment]
   :editor_collection_release
   [:collection
    :release
    :added
    :position
    :comment]
   :editor_collection_release_group
   [:collection
    :release_group
    :added
    :position
    :comment]
   :editor_collection_series
   [:collection
    :series
    :added
    :position
    :comment]
   :editor_collection_work
   [:collection
    :work
    :added
    :position
    :comment]
   :editor_collection_deleted_entity
   [:collection
    :gid
    :added
    :position
    :comment]
   :editor_oauth_token
   [:id
    :editor
    :application
    :authorization_code
    :refresh_token
    :access_token
    :expire_time
    :scope
    :granted]
   :editor_watch_preferences
   [:editor
    :notify_via_email
    :notification_timeframe
    :last_checked]
   :editor_watch_artist
   [:artist
    :editor]
   :editor_watch_release_group_type
   [:editor
    :release_group_type]
   :editor_watch_release_status
   [:editor
    :release_status]
   :medium
   [:id
    :release
    :position
    :format
    :name
    :edits_pending
    :last_updated
    :track_count]
   :medium_attribute_type
   [:id
    :name
    :comment
    :free_text
    :parent
    :child_order
    :description
    :gid]
   :medium_attribute_type_allowed_format
   [:medium_format
    :medium_attribute_type]
   :medium_attribute_type_allowed_value
   [:id
    :medium_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :medium_attribute_type_allowed_value_allowed_format
   [:medium_format
    :medium_attribute_type_allowed_value]
   :medium_attribute
   [:id
    :medium
    :medium_attribute_type
    :medium_attribute_type_allowed_value
    :medium_attribute_text]
   :medium_cdtoc
   [:id
    :medium
    :cdtoc
    :edits_pending
    :last_updated]
   :medium_format
   [:id
    :name
    :parent
    :child_order
    :year
    :has_discids
    :description
    :gid]
   :orderable_link_type
   [:link_type
    :direction]
   :place
   [:id
    :gid
    :name
    :type
    :address
    :area
    :coordinates
    :comment
    :edits_pending
    :last_updated
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :ended]
   :place_alias
   [:id
    :place
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale
    :ended]
   :place_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :place_annotation
   [:place
    :annotation]
   :place_attribute_type
   [:id
    :name
    :comment
    :free_
    :parent
    :child_order
    :description
    :gid]
   :place_attribute_type_allowed_value
   [:id
    :place_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :place_attribute
   [:id
    :place
    :place_attribute_type
    :place_attribute_type_allowed_value
    :place_attribute_]
   :place_gid_redirect
   [:gid
    :new_id
    :created]
   :place_tag
   [:place
    :tag
    :count
    :last_updated]
   :place_tag_raw
   [:place
    :editor
    :tag
    :is_upvote]
   :place_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :replication_control
   [:id
    :current_schema_sequence
    :current_replication_sequence
    :last_replication_date]
   :recording
   [:id
    :gid
    :name
    :artist_credit
    :length
    :comment
    :edits_pending
    :last_updated
    :video]
   :recording_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :recording_alias
   [:id
    :recording
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale
    :ended]
   :recording_rating_raw
   [:recording
    :editor
    :rating]
   :recording_tag_raw
   [:recording
    :editor
    :tag
    :is_upvote]
   :recording_annotation
   [:recording
    :annotation]
   :recording_attribute_type
   [:id
    :name
    :comment
    :free_
    :parent
    :child_order
    :description
    :gid]
   :recording_attribute_type_allowed_value
   [:id
    :recording_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :recording_attribute
   [:id
    :recording
    :recording_attribute_type
    :recording_attribute_type_allowed_value
    :recording_attribute_]
   :recording_meta
   [:id
    :rating
    :rating_count]
   :recording_gid_redirect
   [:gid
    :new_id
    :created]
   :recording_tag
   [:recording
    :tag
    :count
    :last_updated]
   :release
   [:id
    :gid
    :name
    :artist_credit
    :release_group
    :status
    :packaging
    :language
    :script
    :barcode
    :comment
    :edits_pending
    :quality
    :last_updated]
   :release_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :release_alias
   [:id
    :release
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale]
   :release_country
   [:release
    :country
    :date_year
    :date_month
    :date_day]
   :release_unknown_country
   [:release
    :date_year
    :date_month
    :date_day]
   :release_raw
   [:id
    :title
    :artist
    :added
    :last_modified
    :lookup_count
    :modify_count
    :source
    :barcode
    :comment]
   :release_tag_raw
   [:release
    :editor
    :tag
    :is_upvote]
   :release_annotation
   [:release
    :annotation]
   :release_attribute_type
   [:id
    :name
    :comment
    :free_
    :parent
    :child_order
    :description
    :gid]
   :release_attribute_type_allowed_value
   [:id
    :release_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :release_attribute
   [:id
    :release
    :release_attribute_type
    :release_attribute_type_allowed_value
    :release_attribute_]
   :release_gid_redirect
   [:gid
    :new_id
    :created]
   :release_meta
   [:id
    :date_added
    :info_url
    :amazon_asin
    :amazon_store
    :cover_art_presence]
   :release_coverart
   [:id
    :last_updated
    :cover_art_url]
   :release_label
   [:id
    :release
    :label
    :catalog_number
    :last_updated]
   :release_packaging
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :release_status
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :release_tag
   [:release
    :tag
    :count
    :last_updated]
   :release_group
   [:id
    :gid
    :name
    :artist_credit
    :type
    :comment
    :edits_pending
    :last_updated]
   :release_group_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :release_group_alias
   [:id
    :release_group
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale]
   :release_group_rating_raw
   [:release_group
    :editor
    :rating]
   :release_group_tag_raw
   [:release_group
    :editor
    :tag
    :is_upvote]
   :release_group_annotation
   [:release_group
    :annotation]
   :release_group_attribute_type
   [:id
    :name
    :comment
    :free_
    :parent
    :child_order
    :description
    :gid]
   :release_group_attribute_type_allowed_value
   [:id
    :release_group_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :release_group_attribute
   [:id
    :release_group
    :release_group_attribute_type
    :release_group_attribute_type_allowed_value
    :release_group_attribute_]
   :release_group_gid_redirect
   [:gid
    :new_id
    :created]
   :release_group_meta
   [:id
    :release_count
    :first_release_date_year
    :first_release_date_month
    :first_release_date_day
    :rating
    :rating_count]
   :release_group_tag
   [:release_group
    :tag
    :count
    :last_updated]
   :release_group_primary_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :release_group_secondary_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :release_group_secondary_type_join
   [:release_group
    :secondary_type
    :created]
   :script
   [:id
    :iso_code
    :iso_number
    :name
    :frequency]
   :series
   [:id
    :gid
    :name
    :comment
    :type
    :ordering_attribute
    :ordering_type
    :edits_pending
    :last_updated]
   :series_type
   [:id
    :name
    :entity_type
    :parent
    :child_order
    :description
    :gid]
   :series_ordering_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :series_gid_redirect
   [:gid
    :new_id
    :created]
   :series_alias_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :series_alias
   [:id
    :series
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale
    :ended]
   :series_annotation
   [:series
    :annotation]
   :series_attribute_type
   [:id
    :name
    :comment
    :free_
    :parent
    :child_order
    :description
    :gid]
   :series_attribute_type_allowed_value
   [:id
    :series_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :series_attribute
   [:id
    :series
    :series_attribute_type
    :series_attribute_type_allowed_value
    :series_attribute_]
   :series_tag
   [:series
    :tag
    :count
    :last_updated]
   :series_tag_raw
   [:series
    :editor
    :tag
    :is_upvote]
   :tag
   [:id
    :name
    :ref_count]
   :tag_relation
   [:tag1
    :tag2
    :weight
    :last_updated]
   :track
   [:id
    :gid
    :recording
    :medium
    :position
    :number
    :name
    :artist_credit
    :length
    :edits_pending
    :last_updated
    :is_data_track]
   :track_gid_redirect
   [:gid
    :new_id
    :created]
   :track_raw
   [:id
    :release
    :title
    :artist
    :sequence]
   :medium_index
   [:medium
    :toc]
   :url
   [:id
    :gid
    :url
    :edits_pending
    :last_updated]
   :url_gid_redirect
   [:gid
    :new_id
    :created]
   :vote
   [:id
    :editor
    :edit
    :vote
    :vote_time
    :superseded]
   :work
   [:id
    :gid
    :name
    :type
    :comment
    :edits_pending
    :ast_updated]
   :work_language
   [:work
    :language
    :edits_pending
    :created]
   :work_rating_raw
   [:work
    :editor
    :rating]
   :work_tag_raw
   [:work
    :editor
    :tag
    :is_upvote]
   :work_alias_type
   [:id
    :name
    :parent
    :parent
    :child_order
    :description
    :gid]
   :work_alias
   [:id
    :work
    :name
    :locale
    :edits_pending
    :last_updated
    :type
    :sort_name
    :begin_date_year
    :begin_date_month
    :begin_date_day
    :end_date_year
    :end_date_month
    :end_date_day
    :primary_for_locale
    :ended]
   :work_annotation
   [:work
    :annotation]
   :work_gid_redirect
   [:gid
    :new_id
    :created]
   :work_meta
   [:id
    :rating
    :rating_count]
   :work_tag
   [:work
    :tag
    :count
    :last_updated]
   :work_type
   [:id
    :name
    :parent
    :child_order
    :description
    :gid]
   :work_attribute_type
   [:id
    :name
    :comment
    :free_
    :parent
    :child_order
    :description
    :gid]
   :work_attribute_type_allowed_value
   [:id
    :work_attribute_type
    :value
    :parent
    :child_order
    :description
    :gid]
   :work_attribute
   [:id
    :work
    :work_attribute_type :work_attribute_type_allowed_value :work_attribute_text]})