# Docker Compose file for development
version: "2"

volumes:
  cb_home:

services:

  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: critiquebrainz
      POSTGRES_PASSWORD: critiquebrainz
      POSTGRES_DB: critiquebrainz
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata:z
      - ./pg_custom:/docker-entrypoint-initdb.d/
    ports:
      - "15432:5432"

  critiquebrainz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../:/code:z
      - ../data/app:/data:z
      - cb_home:/root
    environment:
      FLASK_APP: critiquebrainz.frontend
      FLASK_ENV: development
    ports:
      - "80:80"
    depends_on:
      - db
      - critiquebrainz_redis
      - musicbrainz_db
      - static_builder

  critiquebrainz_redis:
    image: redis:4.0-alpine

  musicbrainz_db:
    image: metabrainz/musicbrainz-test-database:beta
    volumes:
      - ../data/mbdata:/var/lib/postgresql/data/pgdata:z
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      MB_IMPORT_DUMPS: "true"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5430:5432"

  static_builder:
    build:
      context: ..
      dockerfile: Dockerfile.webpack
    command: npm run dev
    volumes:
      - ..:/code:z
