# Docker Compose file for testing
version: "2"
services:

  db_test:
    image: postgres:12.3
    environment:
      POSTGRES_USER: critiquebrainz
      POSTGRES_PASSWORD: critiquebrainz
      POSTGRES_DB: critiquebrainz
    command: postgres -F
    volumes:
      - ./pg_custom:/docker-entrypoint-initdb.d/
    network_mode: bridge

  musicbrainz_db:
    image: metabrainz/musicbrainz-test-database:beta
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5430:5432"
    network_mode: bridge

  critiquebrainz_redis:
    image: redis:4.0-alpine
    network_mode: bridge

  critiquebrainz_test:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.test
    links:
      - db_test
      - musicbrainz_db
      - critiquebrainz_redis
    network_mode: bridge
